### ISSUE TITLE
ICOM ip address

### ISSUE THREAD

**Issue by iw0red** [n7tae/QnetGateway#13]
Hi, can you show me how change the ICOM ip address? I have changed the cfg file without success.

This is my setup:
Controller ICOM  ip address: 44.162.124.40
PC where the qn software runs: 192.168.2.120
the error message is: Failed to bind 172.16.0.20:20000, errno=99, Cannot assign requested address

My cfg file is:
# Created on Fri May 31 11:13:29 CEST 2019
ircddb_login='IR0UAS'
ircddb_password=''
module_a=icom
module_a_link_at_start='XRF222B'
module_a_callsign='IR0UAS'
module_a_offset=28000
module_a_range=100
module_a_agl=30
module_a_frequency=1270.075
module_a_ip='44.162.124.40'
module_b=icom
module_b_link_at_start='XRF222B'
module_b_callsign='IR0UAS'
module_b_offset=7600
module_b_range=100
module_b_agl=30
module_b_frequency=430.2375
module_b_ip='44.162.124.40'
gateway_url='http://iw0.red'
aprs_host='44.162.124.30'

Thanks in advance.

73 Marco IW0RED.

**Comment by w1bsb** [comment]
Marco

A couple of things.  In a normal ICOM stack setup, the repeater controller uses an IP address of 172.16.0.1, while the gateway uses 172.16.0.20.   Additionally, the controller is not exposed to the internet. It is on a private network that is only between the gateway PC and the repeater itself.  The gateway receives and processes messages from the internet and sends them to the repeater controller.

So first things first. The error message that is printed is because your gateway can't bind to 172.16.0.20 which is the normal gateway address in a repeater stack set up. This is likely due to the fact that you are running your gateway on 192.168.2.120.  So you either need to reprogram the repeater controller and move its IP address to 192.168.2.x, and point it to 192.168.2.120 for the gateway, or leave the settings on the controller at the default and either add a second network interface assigned only to the 172.16.0.20 network on the gateway PC, and a second for the internet, or at the very least, plug the repeater controller into the same hardware serving up your internet connection and use an IP Alias on the gateway PC to access that network.

Additionally, 44.162.124.40 is a routable IP address and should not be assigned to the controller. If this is an address that is assigned to a router, and not a physical machine, QnetGateway will be unable to bind to it as well. QnetGateway can only bind connections on addresses that exist on the machine it is running on.

If your repeater hardware has not been reprogrammed to use different gateway / controller IP addresses, I would simply add another network interface to your gateway's PC and plug the controller into that, and assign the gateway an IP address of 172.16.0.20 with a netmask of 255.255.255.0, and ensure you can then ping the controller from your gateway (172.16.0.1). If you can ping the controller from your gateway, then all you need to do is ensure your gateway has access to the internet, which it should through its already existing 192.168.x.x address. This can be checked with doing something like curl ipinfo.io/ip or ping www.google.com

I'm assuming your router is assigned the 44.x.x.x IP address and not your physical controller/repeater. However, if you manually changed the controller programming and put it on this network, change it back.  I'd love to draw a picture for you of how it should all look, but I really stink at that.

Once the setup is correct, go back into qnconfig and erase all the values you have predefined with IP addresses, and it should start working.

73,

Colby W1BSB

**Comment by iw0red** [comment]
Hi Colby,
first of all, I want to thank you for the detailed answer.
Secondly, I disagree with some assumptions. I try to explain.

1) In a normal ICOM stack setup, the repeater controller uses an IP address of 172.16.0.1, while the gateway uses 172.16.0.20. 
- I agree.

2) Additionally, the controller is not exposed to the internet. It is on a private network that is only between the gateway PC and the repeater itself. 
- Not totally true. Can work on a routed network.

3) The gateway receives and processes messages from the internet and sends them to the repeater controller. 
- True. Even if they are on different networks.

4) The error message that is printed is because your gateway can't bind to 172.16.0.20 which is the normal gateway address in a repeater stack set up.
- True, how can I change it?

 5) This is likely due to the fact that you are running your gateway on 192.168.2.120. So you either need to reprogram the repeater controller and move its IP address to 192.168.2.x, and point it to 192.168.2.120 for the gateway, or leave the settings on the controller at the default and either add a second network interface assigned only to the 172.16.0.20 network on the gateway PC, and a second for the internet, or at the very least, plug the repeater controller into the same hardware serving up your internet connection and use an IP Alias on the gateway PC to access that network.

- As I said, the icom controller/repeaters are on a wide routed network I can't change the controller or gateway ip address. There isn't a network issue. 

5) Additionally, 44.162.124.40 is a routable IP address and should not be assigned to the controller. 

- Why not? It works. The configuration provides IP address, subnet mask, and gateway like a pc.

Finally, the gateway (192.168.2.120) can ping the controller (44.162.124.40), then the gateway has access to the internet. My old setup worked.

-------

gateway = {
        regen_header = true        # regenerate headers from incoming data
        send_qrgs_maps = false      # send frequecy, offset, cooridinates and url to irc-server
        local_irc_ip = "0.0.0.0"   # 0.0.0.0 means accept any incoming connections
        aprs_send = false           # send info to aprs
        ip = "127.0.0.1"           # where the gateway is running

    external = {
                ip = "0.0.0.0"
                port = 40000
        }

        internal = {
                ip = "192.168.2.120"
                port = 20000
        }

-------

module = {
        a = { # an ICOM full stack might consist of up to three module
              # Sorry, the 23 cm data module is not yet supported
          # 23 cm module will use "a"
          # 70 cm module will use "b"
          #  2  M module will use "c"
                type = "icom"      # you must define at least one module by uncommenting the type
                ip = "44.162.124.40" # all icom modules should have the same IP address
                port = 20000       # all icom modules should have the same UDP port
#               frequency = 0      # in MHz, if you specify here, this frequency will show up on the QuadNet USER GATEWAYS webpage
#               offset = 0

73 Marco IW0RED.

**Comment by w1bsb** [comment]
This is not a setup that we can support, or offer support for. Our program is designed around the original ICOM specifications, and that is the only way it was tested and verified to work correctly. Having said that, run qnconfig in expert mode, and under the Gateway menu is the IP address of the gateway (172.16.0.20).

**Comment by iw0red** [comment]
Fine, can I change it?
Marco.

**Comment by w1bsb** [comment]
Yes, in my last reply I listed where to find this setting. Enjoy.

Colby

**Comment by iw0red** [comment]
I changed it but nothing changes as you can see:

root@repeater:~/QnetICOMGateway# ./qngateway qn.cfg
VERSION QnetIcomGateway-0.0.1
Reading Configuration file qn.cfg...
ircddb_login = 'IR0UAS'
OWNER=[IR0UAS]
ircddb_host = 'rr.openquad.net'
ircddb_port = 9007
ircddb_password = ''
gateway_header_regen = true
gateway_send_qrgs_maps = true
gateway_local_irc_ip = '0.0.0.0'
gateway_external_ip = '0.0.0.0'
gateway_external_port = 40000
gateway_internal_ip = '172.16.0.20'
gateway_internal_port = 20000
gateway_healing = false
module_a = 'icom'
module_a_ip = '44.162.124.40'
module_a_port = 20000
module_a_frequency = 1270.08
module_a_offset = 28000
....

73 Marco.

**Comment by w1bsb** [comment]
I changed it on a repeater I have access to and it worked, so I'm not sure what you're doing wrong, but if you modified it in qnconfig expert under Gateway menu, and wrote the changes out with the w command, it should've changed.

May 31 12:20:03 zum qngateway[3769]: ircddb_host = 'rr.openquad.net'
May 31 12:20:03 zum qngateway[3769]: ircddb_port = 9007
May 31 12:20:03 zum qngateway[3769]: ircddb_password = '1111111111111'
May 31 12:20:03 zum qngateway[3769]: gateway_header_regen = true
May 31 12:20:03 zum qngateway[3769]: gateway_send_qrgs_maps = true
May 31 12:20:03 zum qngateway[3769]: gateway_local_irc_ip = '0.0.0.0'
May 31 12:20:03 zum qngateway[3769]: gateway_external_ip = '0.0.0.0'
May 31 12:20:03 zum qngateway[3769]: gateway_external_port = 40000
May 31 12:20:03 zum qngateway[3769]: gateway_internal_ip = '192.168.1.100'
May 31 12:20:03 zum qngateway[3769]: gateway_internal_port = 20000
May 31 12:20:03 zum qngateway[3769]: gateway_healing = false

**Comment by iw0red** [comment]
Fine thanks.
Marco.

**Comment by w1bsb** [comment]
You're welcome. Please close this issue as it does not directly affect this software. The ICOM stack was separated from QnetGateway into its own project, QnetICOMGateway, which is maintained separately. Additionally, this does not appear to be an actual software issue or bug, just a configuration issue which can be solved without source changes. Thank you.

**Comment by iw0red** [comment]
Sure, it works.
Thanks Marco.
