### ISSUE TITLE
Problem during installation

### ISSUE THREAD

**Issue by iw0red** [n7tae/QnetGateway#7]
Hi,
i trying to install the icom version but after the compilation I get this error:

root@voyage:~/QnetGateway# make install
######### QnetGateway #########
/bin/cp -f qngateway /usr/local/bin
/bin/cp -f qnremote qnvoice /usr/local/bin
/bin/ln -s /root/QnetGateway/qn.cfg /usr/local/etc
/bin/cp -f system/qngateway.service /lib/systemd/system
systemctl enable qngateway.service
systemctl daemon-reload
Failed to get D-Bus connection: Unknown error -1
Makefile:89: recipe for target 'install' failed
make: *** [install] Error 1
root@voyage:~/QnetGateway#

73 Marco IW0RED

**Comment by n7tae** [comment]
This is a system level problem. What OS are you installing it on? This error usually means that your OS doesn't have systemd. For example, see https://superuser.com/questions/1173756/cant-start-systemd-failed-to-get-d-bus-connection.

If your system is using sysvinit instead of systemd, I'm sorry but you will have to come up with your own system initialization scripts for the different qn* programs.

A much earlier version of QnetGateway (back when it was called g2_ircddb) used sysvinit. See the "ki4lkf" branch for serveral service.* scripts that might be able to be modified to launch the qn* programs, but they will have to be modified for the new program name, program config file and the program log file. You can also take a look at the Makefile to see how these scripts are installed in a sysvinit OS.

I recommend you move to a Debian stretch-based OS, but if you can't do that, build your own "makefile" ("makefile" will have higher priority than "Makefile") and use your own service scripts. Your new "makefile" will be based on the "master" branch makefile, but you will have replaced the install and uninstall sections with commands that are appropriate for sysvinit.

**Comment by n7tae** [comment]
Looks like voyage 0.11.0 is based on Debian 8.7 which does fully support systemd. It just looks like they have not installed systemd and are using something else, like sysvinit. They may have done this to save on size, since it looks like voyage is designed for the smallest footprint. It also looks like they have no plans to release a voyage based on Debian 9, maybe because they don't like systemd. Since 0.11.0 is based on Debian 8.7, you probably can install systemd (as discussed in the link above), but I obviously can't guarantee it won't break something important. It may be easier (and safer) to follow one of the paths I outlined above.

**Comment by iw0red** [comment]
Fine. May I use screen and this command qngateway qn.cfg?
Marco.

**Comment by n7tae** [comment]
Yes. You can launch manually. If you launch from an ordinary user, make sure that user has write (or read) permission for the various files that will need to be written and read. See the "file" section in the qn.everything.cfg file. You can redefine the paths in your cfg file, or just run as root. If you are connecting to an Icom Stack, you will also need to launch qnlink. If you want DTMF, you'll also have to launch a qndtmf script and possible edit it if qnremote is not in the search path.

**Comment by iw0red** [comment]
Thanks to screen qnetgateway and qnetlink run. I'll try to find the right way.
73 Marco IW0RED
